repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: '^camb/.*\.(py|ipynb|f90)$'
      - id: end-of-file-fixer
        files: '^camb/.*\.(py|ipynb|f90)$'
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
