name: Valgrind Memory Check

on:
  push:
  pull_request:

jobs:
  valgrind-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Run CAMB with Valgrind in Docker
      run: |
        docker run --rm -v "$(pwd):/workspace" -w /workspace cmbant/docker-gcc-build:gcc15 bash -c "
            echo 'Building CAMB...' &&
            cd fortran && make clean && make > /dev/null 2>&1 &&
            echo 'Running CAMB with valgrind...' &&
            valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all ./camb 
        "

